### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NJannasch**
Formatting improved

### CODE REVIEW

**Review by cadriel — COMMENTED** [review]
Does there need to be two individual code blocks now?

Secondarily - I think the directory change line doesn't make sense, or is unnecessarily split across two lines..

Maybe combine it into one block and fix the cd line.. :)

**Comment by cadriel** [comment]
@NJannasch Can you rebase this.. also, did you make the changes suggested?

**Comment by NJannasch** [comment]
Will check this on Saturday! 👍

**Comment by NJannasch** [comment]
Done :-)

**Comment by cadriel** [comment]
Looks good!

**Pull request merged**
